name: Code Quality Checks

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  clang-format:
    name: Clang-Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Clang-Format Check
        uses: jidicula/clang-format-action@v4.11.0
        with:
          clang-format-version: '14'
          check-path: '.'
          exclude-regex: 'extern|build'

  cppcheck:
    name: Cppcheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Cppcheck
        run: sudo apt-get install -y cppcheck
      - name: Run Cppcheck
        run: cppcheck --enable=all --std=c++17 --error-exitcode=1 --suppress=missingIncludeSystem --suppress=unmatchedSuppression --inline-suppr include/ src/ apps/ -i extern/